package numbers.filter;

public enum FilterType {
    EVEN, ODD, BUZZ, DUCK, PALINDROMIC, GAPFUL, SPY, SQUARE, SUNNY, JUMPING, HAPPY, SAD, NOT_EVEN, NOT_ODD, NOT_BUZZ,
    NOT_DUCK, NOT_PALINDROMIC, NOT_GAPFUL, NOT_SPY, NOT_SQUARE, NOT_SUNNY, NOT_JUMPING, NOT_HAPPY, NOT_SAD
}
